Added ldap helper
Network-Rail-Business-Systems/user-login pull request #3
Opened 2024-10-31 16:17 UTC by SimRoberts9

2024-11-01 08:02 UTC, AnthonyEdmonds requested changes

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/SearchByNameTest.php
> +            $mock->shouldReceive('query->where->orWhere->andFilter->select->limit->get')
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/SearchByEmailTest.php
> +            $mock->shouldReceive('query->where->andFilter->select->limit->get')
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +            $mock->shouldReceive('query->where->andFilter->select->limit->get')
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +            $mock->shouldReceive('call')
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +            $mock->shouldReceive('query->where->andFilter->select->limit->get')
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +                ->andReturnUsing(function () {
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +            $mock->shouldReceive('query->where->andFilter->select->limit->get')
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +                ->andReturnUsing(function () {
Add `once` to the chain to formalise the assertion.

2024-11-01 08:02 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
DRY. Add helper function to define mocks instead of repeating yourself.

2024-11-04 14:13 UTC, AnthonyEdmonds requested changes

2024-11-04 14:13 UTC, AnthonyEdmonds commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +        $this->expectException(\ErrorException::class);
Import class

2024-11-04 14:15 UTC, SimRoberts9 commented on tests/Unit/Helpers/LdapHelper/ImportTest.php
> +        $this->expectException(\ErrorException::class);
Done, thank you!

2024-11-04 14:24 UTC, AnthonyEdmonds approved these changes

2024-11-04 14:26 UTC, merged